Options:
	prefix: &6[&eCommands Script&6]&r
	consolePrefix: &6[&8Console&6]&r

on script load:
	consoleMessage("Loaded!")

on script unload:
	consoleMessage("Unloading...")

local function consoleMessage(message: text):
	send "{@consolePrefix} {@prefix} &e%{_message}%" to console

command /console <text>:
	trigger:
		command executor is console
		broadcast "&e<console>&c: &6%argument%"

command /list-attributes:
	trigger:
		loop all attribute types:
			message "%loop-value%" 

